name: dacodes_dd3
description: Prueba técnica para DaCodes<>DD3

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+4
  number_paginator: ^0.2.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.0
  


dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  patrol: ^1.0.9
  very_good_analysis: ^4.0.0+1

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_intl:
  main_locale: es
  enabled: true

patrol:
  app_name: Dacodes Dd3
  android:
    package_name: com.example.dacodes_dd3
  ios:
    bundle_id: com.example.dacodes_dd3